### REDDIT API Connexion

In [1]:
CLIENT_ID = 'id de l application reddit'
SECRET = 'code secret de l application'

In [3]:
import requests
import pandas as pd
import csv
import time
from datetime import datetime



In [3]:
auth = requests.auth.HTTPBasicAuth(CLIENT_ID, SECRET)

In [4]:
data = {
    'grant_type' : 'password', 
    'username' : '', 
    'password' : '' 
}

In [5]:
headers = {'User-Agent': 'MyAPI/0.0.1'}

In [7]:
res  = requests.post('https://www.reddit.com/api/v1/access_token', 
                    auth=auth, data=data, headers = headers)

In [8]:
TOKEN = res.json()['access_token']

In [9]:
TOKEN

'eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzAxNzE3NDQyLjkzNTE1NSwiaWF0IjoxNzAxNjMxMDQyLjkzNTE1NSwianRpIjoiZHlZS0NHaExRTjFPb3ozNzJaMmNwTmNKNExOeUFRIiwiY2lkIjoiQmlxSUVQUnpnS3JlZ1pRTTdscmk0dyIsImxpZCI6InQyXzVqaHR1aDZ1IiwiYWlkIjoidDJfNWpodHVoNnUiLCJsY2EiOjE1ODAxNDg4MTc2OTksInNjcCI6ImVKeUtWdEpTaWdVRUFBRF9fd056QVNjIiwiZmxvIjo5fQ.XepFoG_xYzMlxpJHptdjCDhXFhJGbjBecwVqmCeyhjK3YeqkpzSkVoqDWeOuSUyzluONqLeBuTG6iBJKRf-xYbeAoIIW0D6TkspW6gM29jVvMwt-w_zu2pwO3r45st3ejDClyqsqTJxefAt-O5fuZ9Hty5V7xssYpCe3nwn_tWbijWdbXBtcC5mxyualW7fYiMJbJ5vFDY-SlnfESwW-fsQ1XT4SNsKAlANyfm5wv-Z6xll_W7UVCi-S_vDMZzawszNBtVa5-ha4XD6zpnVH5iq3sLX8gvREm8oe61FTmM-tE8mz6HIO2QC53guABEcClUQ_djUEjLM5eLLNPR2iag'

In [10]:
headers = {**headers, **{'Authorization': f'bearer {TOKEN}'}}

In [11]:
headers

{'User-Agent': 'MyAPI/0.0.1',
 'Authorization': 'bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzAxNzE3NDQyLjkzNTE1NSwiaWF0IjoxNzAxNjMxMDQyLjkzNTE1NSwianRpIjoiZHlZS0NHaExRTjFPb3ozNzJaMmNwTmNKNExOeUFRIiwiY2lkIjoiQmlxSUVQUnpnS3JlZ1pRTTdscmk0dyIsImxpZCI6InQyXzVqaHR1aDZ1IiwiYWlkIjoidDJfNWpodHVoNnUiLCJsY2EiOjE1ODAxNDg4MTc2OTksInNjcCI6ImVKeUtWdEpTaWdVRUFBRF9fd056QVNjIiwiZmxvIjo5fQ.XepFoG_xYzMlxpJHptdjCDhXFhJGbjBecwVqmCeyhjK3YeqkpzSkVoqDWeOuSUyzluONqLeBuTG6iBJKRf-xYbeAoIIW0D6TkspW6gM29jVvMwt-w_zu2pwO3r45st3ejDClyqsqTJxefAt-O5fuZ9Hty5V7xssYpCe3nwn_tWbijWdbXBtcC5mxyualW7fYiMJbJ5vFDY-SlnfESwW-fsQ1XT4SNsKAlANyfm5wv-Z6xll_W7UVCi-S_vDMZzawszNBtVa5-ha4XD6zpnVH5iq3sLX8gvREm8oe61FTmM-tE8mz6HIO2QC53guABEcClUQ_djUEjLM5eLLNPR2iag'}

## Récupération des comptes 

In [12]:
params = {
    'limit': 15000,  # Limite le nombre de résultats à 100 par page
    'after': None  # Permet de récupérer les résultats suivants
}

In [13]:

def recupAccounts(subName):
    i = 0
    df = pd.DataFrame()
    url = f'https://oauth.reddit.com/r/{subName}/hot'
    while True:
        response = requests.get(url, headers=headers, params=params)
        i +=1
        print(i)
        if i == 1000:
            break
        if response.status_code == 200:
            data = response.json()
            for post in data['data']['children']:
                #df = df.append({'author':post['data']['author']}, ignore_index=True)
                new_row = pd.DataFrame({'author': [post['data']['author']]})

                df = pd.concat([df, new_row], ignore_index=True)

            
            # Mettez à jour le paramètre 'after' pour obtenir les résultats suivants
            params['after'] = data['data']['after']


            # Arrêtez la boucle si 'after' est None, ce qui signifie qu'il n'y a plus de résultats à récupérer
            if params['after'] is None:
                break
    return df

In [14]:
TopSubReddit = pd.read_csv('ultimatelist.csv') 


### Récupération des subReddit d'un compte

In [15]:
def recupSubReddit(username):
    dfSub = pd.DataFrame()
    after = None
    headers = {'User-Agent': 'MyAPI/0.0.1'}  # Assurez-vous d'avoir un User-Agent valide

    while True:
        urlDos = f'https://www.reddit.com/user/{username}/submitted.json'
        params = {'after': after} if after else {}
        response = requests.get(urlDos, headers=headers, params=params)

        if response.status_code == 200:
            submissions = response.json()['data']['children']
            for submission in submissions:
                new_row = pd.DataFrame({username: [submission['data']['subreddit']]}, index=[0])
                dfSub = pd.concat([dfSub, new_row], ignore_index=True)

            after = response.json()['data']['after']

            if not after:
                break
        elif response.status_code == 404:
            print(f"Utilisateur {username} non trouvé.")
            break
        elif response.status_code == 429:
            reset_time = int(response.headers['x-ratelimit-reset'])
            current_time = int(time.time())

            # Calcule le temps d'attente jusqu'à la réinitialisation du taux limite
            wait_time = max(0, reset_time - current_time) + 20  # Ajoute un délai supplémentaire de 5 secondes

            print(f"Erreur 429 - Trop de requêtes. Attendez {wait_time} secondes avant de réessayer.")
            time.sleep(wait_time)
        else:
            print(f"La requête a échoué avec le code d'état {response.status_code}")
            break
            
    return dfSub

In [16]:
def recupAutoSub(acounts):
    dfs = []
    i = 0
    for compte in acounts.itertuples(index=False):
        print(i)
        if i == 200:
            break
        i += 1
        username = compte.author
        if username != '[deleted]' and username:  
            df_sub = recupSubReddit(username).drop_duplicates()
            dfs.append(df_sub)

    df_result = pd.concat(dfs, axis=1)
    return df_result



In [18]:
def mainFonct(nbSub):
    for i in range(53, nbSub):
        print(i)
        sub_name = TopSubReddit['announcements'][i]
        print(sub_name)
        
        # Appel de la fonction recupAccounts
        df_accounts = recupAccounts(sub_name)
        
        # Affichage du DataFrame
        print(df_accounts)
        
        # Affichage de la forme du DataFrame
        print(df_accounts.shape)

        maintenant = datetime.now()
        date_heure_lisible = maintenant.strftime("%d-%m-%Y %H:%M:%S")
        print(f"\n\n\nDébut de {sub_name}\n {date_heure_lisible}\n\n\n")
        
        df_result = recupAutoSub(df_accounts)
        df_result.to_csv(f'CSV/{TopSubReddit["announcements"][i]}', index=False)

        maintenant = datetime.now()
        date_heure_lisible = maintenant.strftime("%d-%m-%Y %H:%M:%S")
        print(f"\n\n\Fin de {sub_name}\n {date_heure_lisible}\n\n\n")




In [19]:
mainFonct(55) #74

53
politics
1
2
3
4
5
6
7
8
              author
0           optimalg
1        StyleMavens
2           Majano57
3     outspoken33334
4    areallycleverid
..               ...
733  PresidentSpanky
734       AudibleNod
735      newsspotter
736   Chemist-Minute
737           3kOlen

[738 rows x 1 columns]
(738, 1)



Début de politics
 03-12-2023 20:18:47



0
1
2
3
4
5
6
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes avant de réessayer.
Erreur 429 - Trop de requêtes. Attendez 20 secondes 

In [8]:
import pandas as pd
import networkx as nx
from networkx.algorithms import bipartite

df = pd.read_csv("3000liens.csv")

G = nx.Graph()

utilisateurs = sorted(set(df['Utilisateur']))
subreddits = sorted(set(df['Subreddit']))
subs = pd.DataFrame({'Id': subreddits, 'Label': subreddits})
print(subs)
subs.to_csv("noeuds3000subs.csv", index=False)

"""edges = [(row['Utilisateur'], row['Subreddit']) for _, row in df.iterrows()]
G.add_nodes_from(utilisateurs, bipartite=0)
G.add_nodes_from(subreddits, bipartite=1)
G.add_edges_from(edges)

#adj_matrix = nx.adjacency_matrix(G).todense()
adj_matrix = nx.bipartite.biadjacency_matrix(G, row_order=utilisateurs, column_order=subreddits).todense()"""

                  Id           Label
0        100yearsago     100yearsago
1       1200isplenty    1200isplenty
2             13or30          13or30
3              18_19           18_19
4          2007scape       2007scape
...              ...             ...
2730    youtubehaiku    youtubehaiku
2731  youtubetitties  youtubetitties
2732          yugioh          yugioh
2733             zen             zen
2734         zombies         zombies

[2735 rows x 2 columns]


"edges = [(row['Utilisateur'], row['Subreddit']) for _, row in df.iterrows()]\nG.add_nodes_from(utilisateurs, bipartite=0)\nG.add_nodes_from(subreddits, bipartite=1)\nG.add_edges_from(edges)\n\n#adj_matrix = nx.adjacency_matrix(G).todense()\nadj_matrix = nx.bipartite.biadjacency_matrix(G, row_order=utilisateurs, column_order=subreddits).todense()"

In [16]:
df2 = pd.read_csv("liens3000subs.csv")
liste2 = [(row['Source'], row['Target']) for _,row in df2.iterrows()]
for i in liste2 :
    if i[0] == i[1] :
        liste2.remove(i)

print(liste2[:6])

[('1200isplenty', 'AskReddit'), ('1200isplenty', 'food'), ('1200isplenty', 'pics'), ('13or30', 'AdviceAnimals'), ('13or30', 'AskReddit'), ('13or30', 'CrappyDesign')]


In [17]:
import csv
with open("liens3000subsNoBoucle.csv", 'w', newline='') as fichier_csv:
    writer = csv.writer(fichier_csv)
    # Écrire les en-têtes si nécessaire
    writer.writerow(['Source', 'Target'])
    # Écrire les données
    writer.writerows(liste2)

In [3]:
import numpy as np

adj_matrix = np.array(adj_matrix)
#produit = adj_matrix.T*adj_matrix
result = np.dot(adj_matrix.T, adj_matrix)

# Créer un DataFrame avec la matrice d'adjacence
#adj_df = pd.DataFrame(produit, index=utilisateurs, columns=subreddits)

print(result)
print(result.shape)
#print(adj_df)
#adj_df.to_csv("3000f.csv")

[[ 6  0  1 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 1  0 51 ...  1  0  0]
 ...
 [ 0  0  1 ... 94  0  1]
 [ 0  0  0 ...  0  5  0]
 [ 0  0  0 ...  1  0 33]]
(2735, 2735)


In [5]:
print(result)
print(np.max(result))
resultDup = np.copy(result)
print(np.max(resultDup))
print(np.size(resultDup))

[[ 6  0  1 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 1  0 51 ...  1  0  0]
 ...
 [ 0  0  1 ... 94  0  1]
 [ 0  0  0 ...  0  5  0]
 [ 0  0  0 ...  1  0 33]]
3978
3978
7480225


In [39]:
# Utilisez np.logical_and pour créer un masque booléen pour les valeurs dans l'intervalle
masque_intervalle = np.logical_and(resultDup >= 10, resultDup < 50)

# Comptez le nombre de valeurs dans l'intervalle en utilisant np.sum sur le masque
nombre_de_valeurs_dans_intervalle = np.sum(masque_intervalle)

nombre_de_valeurs_egal_a_valeur = np.count_nonzero(resultDup == 0)

print(nombre_de_valeurs_egal_a_valeur)

7297776


In [33]:
resultDup[resultDup < 10] = 0
resultDup[(resultDup >= 10) & (resultDup < 50)] = 1
resultDup[(resultDup >= 50) & (resultDup < 100)] = 2
resultDup[(resultDup >= 100) & (resultDup < 500)] = 3
resultDup[resultDup >= 500] = 4
print(np.max(resultDup))

print(result)
print(resultDup)

4
[[ 6  0  1 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 1  0 51 ...  1  0  0]
 ...
 [ 0  0  1 ... 94  0  1]
 [ 0  0  0 ...  0  5  0]
 [ 0  0  0 ...  1  0 33]]
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [55]:
print(subreddits)
adj_df = pd.DataFrame(resultDup, index=subreddits, columns=subreddits)
print(adj_df)
adj_df.to_csv("3000f2.csv")

['100yearsago', '1200isplenty', '13or30', '18_19', '2007scape', '2busty2hide', '2healthbars', '2meirl4meirl', '30ROCK', '3DS', '3Dprinting', '3amjokes', '3dshacks', '49ers', '4chan', '60fpsporn', 'ABoringDystopia', 'ABraThatFits', 'ADHD', 'AMA', 'AMADisasters', 'ANormalDayInRussia', 'ARK', 'ATBGE', 'AbandonedPorn', 'AccidentalComedy', 'AccidentalRacism', 'AccidentalRenaissance', 'AccidentalWesAnderson', 'Accounting', 'ActLikeYouBelong', 'AdPorn', 'Addons4Kodi', 'AdrenalinePorn', 'AdrianaChechik', 'AdvancedFitness', 'Advice', 'AdviceAnimals', 'AfterEffects', 'AgainstHateSubreddits', 'AgedBeauty', 'AirForce', 'AlbumArtPorn', 'AlienBlue', 'AliensAmongUs', 'AlisonBrie', 'Allsvenskan', 'AmItheAsshole', 'Amateur', 'AmateurPorn', 'AmateurRoomPorn', 'Amd', 'AmericanHorrorStory', 'AnalGW', 'Anarchism', 'Anarcho_Capitalism', 'Android', 'AndroidGaming', 'AndroidQuestions', 'AndroidWear', 'AngelaWhite', 'AnimalCrossing', 'AnimalPorn', 'AnimalTextGifs', 'AnimalsBeingBros', 'AnimalsBeingConfused', '

In [52]:
indices = np.argwhere(resultDup != 0)

print(indices)

edge_list = [(subreddits[index[0]], subreddits[index[1]], resultDup[index[0], index[1]]) for index in indices]

print("Edge List:")

print(edge_list[:6])

[[   1    1]
 [   1  110]
 [   1 1735]
 ...
 [2734 2576]
 [2734 2642]
 [2734 2734]]
Edge List:
[('1200isplenty', '1200isplenty', 1), ('1200isplenty', 'AskReddit', 1), ('1200isplenty', 'food', 1), ('1200isplenty', 'pics', 1), ('13or30', '13or30', 2), ('13or30', 'AdviceAnimals', 1)]


In [54]:
import csv
with open("liens3000subs.csv", 'w', newline='') as fichier_csv:
    writer = csv.writer(fichier_csv)
    # Écrire les en-têtes si nécessaire
    writer.writerow(['Source', 'Target', 'Class'])
    # Écrire les données
    writer.writerows(edge_list)